  CREATE TABLE "PROJECTS" 
   ("ID" NUMBER(19,0), 
	"PR_DESCRIPTION" VARCHAR2(4000 CHAR), 
	"PR_NAME" VARCHAR2(127 CHAR) NOT NULL,
	"PR_VALUE" NUMBER(10,0),
	constraint PROJECTS_PK primary key (ID),
	constraint PROJECTS_PR_NAME_UK unique (PR_NAME)
   );

  CREATE TABLE "USERS" 
   ("ID" NUMBER(19,0), 
	"IS_ADMIN" NUMBER(1,0), 
	"FIRST_NAME" VARCHAR2(35 CHAR) NOT NULL, 
	"LAST_NAME" VARCHAR2(35 CHAR) NOT NULL, 
	"USER_LOGIN" VARCHAR2(35 CHAR) NOT NULL, 
	"PASSWORD" VARCHAR2(128 CHAR) NOT NULL,
	constraint USERS_PK primary key (ID),
	constraint USERS_USER_LOGIN_UK unique (USER_LOGIN)
   );


  CREATE TABLE "REQUIREMENTS" 
   ("ID" NUMBER(19,0), 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	"NAME" VARCHAR2(127 CHAR) NOT NULL, 
	"PROJECT_ID" NUMBER(19,0),
	"ROUND" NUMBER(10,0),
	"REQ_VALUE" NUMBER(10,0),
	constraint REQUIREMENTS_PK primary key (ID),
	constraint REQUIREMENTS_PROJECT_ID_FK foreign key (PROJECT_ID) references PROJECTS(ID),
	constraint REQUIREMENTS_NAME_UK unique (NAME)
   );
   
  CREATE TABLE "PROJECT_EXPERTS" 
   ("PROJECT_ID" NUMBER(19,0), 
	"USER_ID" NUMBER(19,0),
	constraint PROJECT_EXPERTS_USER_ID_FK foreign key (USER_ID) references USERS(ID),
	constraint PROJECT_EXPERTS_PROJECT_ID_FK foreign key (PROJECT_ID) references PROJECTS(ID)
   );
   
     CREATE TABLE "ESTIMATIONS"
   ("ID" NUMBER(19,0), 
	"EST_COMMENT" VARCHAR2(500 CHAR), 
	"HAS_RATED" NUMBER(1,0), 
	"EST_UPDATED" NUMBER(1,0), 
	"EST_VALUE" NUMBER(10,0), 
	"REQUIREMENT_ID" NUMBER(19,0), 
	"USER_ID" NUMBER(19,0),
	constraint ESTIMATIONS_PK primary key (ID),
	constraint ESTIMATIONS_USER_ID_FK foreign key (USER_ID) references USERS(ID),
	constraint ESTIMATIONS_REQUIREMENT_ID_FK foreign key (REQUIREMENT_ID) references REQUIREMENTS(ID)
   );

  CREATE TABLE "ESTIMATIONS_HISTORY" 
   ("ID" NUMBER(19,0), 
	"EST_COMMENT" VARCHAR2(500 CHAR), 
	"UPDATE_TIME" TIMESTAMP (6), 
	"EST_VALUE" NUMBER(10,0), 
	"REQUIREMENT_ID" NUMBER(19,0), 
	"USER_ID" NUMBER(19,0),
	constraint ESTIMATIONS_HISTORY_PK primary key (ID),
	constraint ESTIMATIONS_HIS_USER_ID_FK foreign key (USER_ID) references USERS(ID),
	constraint ESTIMATIONS_HIS_REQ_ID_FK foreign key (REQUIREMENT_ID) references REQUIREMENTS(ID)
   );
   
Insert into PLANNING_POKER.USERS (ID,IS_ADMIN,FIRST_NAME,LAST_NAME,USER_LOGIN,PASSWORD) values (22,1,'asda','asda','asda','asdasd');
	  